import Head from "next/head";
import React from "react";

export const HeadSet = () => {
  const title = "BlockSight";
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" />
    </Head>
  );
};
